### ISSUE TITLE
Ошибка при запуске  field required (type=value_error.missing)

### ISSUE THREAD

**Issue by helix4d** [MasterGroosha/telegram-feedback-bot#14]
Пробовал Python 3.10 и 3.11, разные версии aiogram и pydantic
python3.10 -m bot
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mk/telegram-feedback-bot_ktu_priyom/bot/__main__.py", line 10, in <module>
    from bot.commandsworker import set_bot_commands
  File "/home/mk/telegram-feedback-bot_ktu_priyom/bot/commandsworker.py", line 4, in <module>
    from bot.config_reader import config
  File "/home/mk/telegram-feedback-bot_ktu_priyom/bot/config_reader.py", line 22, in <module>
    config = Settings()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for Settings
bot_token
  field required (type=value_error.missing)
admin_chat_id
  field required (type=value_error.missing)
remove_sent_confirmation
  field required (type=value_error.missing)

**Comment by MasterGroosha** [comment]
Привет, судя по ошибке, вы не передаёте никакие настройки в бота. Как запускаете?

**Comment by helix4d** [comment]
> Привет, судя по ошибке, вы не передаёте никакие настройки в бота. Как запускаете?

Спасибо, что ответили. Посмотрел, во время переименования не набрал точку в .env
Исправил, все работает.
Бот отличный. Поднимал два (без докера через systemd), uptime по полгода, все работало как часы.
